/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: assetfactory (https://sketchfab.com/assetfactory)
license: SKETCHFAB Standard (https://sketchfab.com/licenses)
source: https://sketchfab.com/3d-models/skateboard-59552a6040fe4f8d8510d3b17ac5abbd
title: Skateboard
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/skate.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.skateboard} />
      </group>
    </group>
  )
}

useGLTF.preload('/skate.gltf')
