PATCH http://localhost:3000/users/levelUp/623cc972c7b50b53c0fcc74a HTTP/1.1

Content-Type: {application/json}

{
    "trickId": "623c6a84f4146e38fe7d8222",
    "trickStat": 75
}

###

PATCH http://localhost:3000/users/623cc972c7b50b53c0fcc74a HTTP/1.1

Content-Type: {application/json}

{
    "xp": 500
}